#!/usr/bin/env python3
"""Generate an HTML report from a Portolan scan JSON file.

Usage:
    python3 report.py /tmp/portolan-music-scan.json
    python3 report.py /tmp/portolan-music-scan.json --out report.html
"""

import json
import math
import sys
from pathlib import Path

# Language colors — similar to GitHub's but tuned for light backgrounds
LANG_COLORS = {
    "rust": "#dea584",
    "purescript": "#1d222d",
    "erlang": "#b83998",
    "python": "#3572a5",
    "javascript": "#f1e05a",
    "typescript": "#3178c6",
    "node": "#f1e05a",
    "c": "#555555",
    "cpp": "#f34b7d",
    "go": "#00add8",
    "ruby": "#701516",
    "java": "#b07219",
    "kotlin": "#a97bff",
    "haskell": "#5e5086",
    "elixir": "#6e4a7e",
    "html": "#e34c26",
    "css": "#563d7c",
    "shell": "#89e051",
    "sql": "#e38c00",
    "json": "#999999",
    "yaml": "#cb171e",
    "toml": "#9c4221",
    "markdown": "#083fa1",
    "make": "#427819",
    "lua": "#000080",
}

def lang_color(lang):
    return LANG_COLORS.get(lang, "#aaaaaa")


def pie_wedge(cx, cy, r, fraction, fill):
    """SVG path for a pie wedge starting from 12 o'clock, clockwise."""
    angle = fraction * 2 * math.pi
    start_x = cx
    start_y = cy - r
    end_x = cx + r * math.sin(angle)
    end_y = cy - r * math.cos(angle)
    large_arc = 1 if fraction > 0.5 else 0
    return (
        f'<path d="M {cx} {cy} L {start_x} {start_y} '
        f'A {r} {r} 0 {large_arc} 1 {end_x:.1f} {end_y:.1f} Z" '
        f'fill="{fill}" opacity="0.9"/>'
    )


def generate_report(scan_data):
    components = scan_data["components"]
    connections = scan_data.get("connections", [])
    languages = scan_data["languages"]

    # Filter to interesting components (skip toolchain noise)
    interesting = [c for c in components if not any(
        skip in c["path"] for skip in ("arm-gnu-toolchain", "arm-none-eabi", ".psci_modules")
    )]

    # Cluster components into subsystems by path prefix
    clusters = cluster_components(interesting)

    # Build the HTML
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Portolan Report</title>
<style>
{CSS}
</style>
</head>
<body>
<header>
    <h1>Portolan</h1>
    <p class="subtitle">System scan of <code>{scan_data['root']}</code></p>
</header>

<main>
{generate_summary_section(scan_data, interesting)}
{generate_topology_section(interesting, connections, clusters)}
{generate_treemap_section(interesting, languages)}
{generate_flow_section(interesting, connections)}
{generate_component_table(interesting, connections)}
</main>

<footer>
    <p>Generated by Portolan &mdash; system-level explorer for multi-component projects</p>
</footer>
</body>
</html>"""

    return html


CSS = """
* { margin: 0; padding: 0; box-sizing: border-box; }
body {
    font-family: -apple-system, 'Helvetica Neue', Helvetica, Arial, sans-serif;
    background: #fafafa;
    color: #1a1a1a;
    line-height: 1.6;
    max-width: 1100px;
    margin: 0 auto;
    padding: 2rem;
}
header {
    margin-bottom: 3rem;
    border-bottom: 3px solid #1a1a1a;
    padding-bottom: 1rem;
}
header h1 {
    font-size: 2.5rem;
    font-weight: 700;
    letter-spacing: -0.02em;
}
header .subtitle {
    color: #666;
    font-size: 0.95rem;
    margin-top: 0.25rem;
}
header .subtitle code {
    background: #eee;
    padding: 0.15em 0.4em;
    border-radius: 3px;
    font-size: 0.85em;
}
main section {
    margin-bottom: 3rem;
}
h2 {
    font-size: 1.3rem;
    font-weight: 600;
    margin-bottom: 1rem;
    border-bottom: 1px solid #ddd;
    padding-bottom: 0.4rem;
}
h3 {
    font-size: 1.05rem;
    font-weight: 600;
    margin-bottom: 0.5rem;
    color: #333;
}
p, li {
    font-size: 0.92rem;
    margin-bottom: 0.5rem;
}
.stats-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
    gap: 1rem;
    margin: 1rem 0;
}
.stat-card {
    background: white;
    border: 1px solid #e0e0e0;
    border-radius: 6px;
    padding: 1rem;
    text-align: center;
}
.stat-card .number {
    font-size: 2rem;
    font-weight: 700;
    display: block;
    line-height: 1.2;
}
.stat-card .label {
    font-size: 0.8rem;
    color: #666;
    text-transform: uppercase;
    letter-spacing: 0.05em;
}
.figure {
    background: white;
    border: 1px solid #e0e0e0;
    border-radius: 6px;
    padding: 1.5rem;
    margin: 1.5rem 0;
}
.figure svg {
    display: block;
    margin: 0 auto;
}
.figure-caption {
    text-align: center;
    font-size: 0.82rem;
    color: #888;
    margin-top: 0.75rem;
    font-style: italic;
}
table {
    width: 100%;
    border-collapse: collapse;
    font-size: 0.85rem;
    margin-top: 1rem;
}
th, td {
    text-align: left;
    padding: 0.5rem 0.75rem;
    border-bottom: 1px solid #eee;
}
th {
    font-weight: 600;
    font-size: 0.75rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: #666;
    border-bottom: 2px solid #ddd;
}
tr:hover td { background: #f8f8f8; }
.role-badge {
    display: inline-block;
    font-size: 0.7rem;
    font-weight: 600;
    padding: 0.15em 0.5em;
    border-radius: 3px;
    text-transform: uppercase;
    letter-spacing: 0.03em;
}
.role-service { background: #e8f5e9; color: #2e7d32; }
.role-executable { background: #e3f2fd; color: #1565c0; }
.role-library { background: #f3e5f5; color: #7b1fa2; }
.role-workspace-root { background: #fff3e0; color: #e65100; }
.role-unknown { background: #eee; color: #666; }
.lang-dot {
    display: inline-block;
    width: 10px;
    height: 10px;
    border-radius: 50%;
    margin-right: 0.4em;
    vertical-align: middle;
}
.legend {
    display: flex;
    flex-wrap: wrap;
    gap: 1rem;
    margin: 1rem 0;
    font-size: 0.82rem;
}
.legend-item {
    display: flex;
    align-items: center;
    gap: 0.3rem;
}
footer {
    margin-top: 3rem;
    padding-top: 1rem;
    border-top: 1px solid #ddd;
    text-align: center;
    color: #999;
    font-size: 0.8rem;
}
"""


def cluster_components(components):
    """Group components into subsystems by path prefix."""
    clusters = {}
    for c in components:
        path = c["path"]
        if path.startswith("live-coding/calypso"):
            cluster = "calypso"
        elif path.startswith("live-coding/"):
            cluster = "live-coding"
        elif path.startswith("expert-sleepers/"):
            cluster = "expert-sleepers"
        elif path.startswith("SamplesProject/"):
            cluster = "samples"
        elif path.startswith("rig-control/"):
            cluster = "rig-control"
        else:
            cluster = "other"
        clusters.setdefault(cluster, []).append(c)
    return clusters


def generate_summary_section(scan_data, components):
    languages = scan_data["languages"]
    connections = scan_data.get("connections", [])
    total_loc = sum(v["loc"] for v in languages.values())
    services = sum(1 for c in components if c["role"] == "service")
    libs = sum(1 for c in components if c["role"] == "library")
    exes = sum(1 for c in components if c["role"] in ("executable", "binary"))

    lang_items = sorted(languages.items(), key=lambda x: -x[1]["loc"])
    # Filter to authored languages (skip vendored/generated)
    authored_loc = sum(v["loc"] for k, v in languages.items()
                       if k not in ("c", "cpp", "html"))

    return f"""
<section>
    <h2>Overview</h2>
    <div class="stats-grid">
        <div class="stat-card">
            <span class="number">{len(components)}</span>
            <span class="label">Components</span>
        </div>
        <div class="stat-card">
            <span class="number">{services}</span>
            <span class="label">Services</span>
        </div>
        <div class="stat-card">
            <span class="number">{len(connections)}</span>
            <span class="label">Connections</span>
        </div>
        <div class="stat-card">
            <span class="number">{len(languages)}</span>
            <span class="label">Languages</span>
        </div>
    </div>
</section>"""


def generate_topology_section(components, connections, clusters):
    """Generate the system topology SVG."""
    W, H = 1000, 620

    # Position clusters in regions
    cluster_centers = {
        "live-coding": (300, 200),
        "calypso": (300, 430),
        "expert-sleepers": (750, 200),
        "samples": (750, 480),
        "rig-control": (900, 350),
        "other": (550, 530),
    }

    # Position individual components within clusters
    positions = {}
    for cluster_name, cluster_comps in clusters.items():
        cx, cy = cluster_centers.get(cluster_name, (500, 300))
        n = len(cluster_comps)
        for i, comp in enumerate(cluster_comps):
            angle = (2 * math.pi * i / max(n, 1)) - math.pi / 2
            r = min(60, 25 * n)
            x = cx + r * math.cos(angle)
            y = cy + r * math.sin(angle)
            positions[comp["name"]] = (x, y)

    # Build SVG
    svg_parts = [f'<svg viewBox="0 0 {W} {H}" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;">']

    # Cluster backgrounds
    cluster_labels = {
        "live-coding": "Live-Coding Engine",
        "calypso": "Calypso Editor",
        "expert-sleepers": "Hardware Interface",
        "samples": "Sample Management",
        "rig-control": "Rig Control",
        "other": "Other",
    }
    for cluster_name, cluster_comps in clusters.items():
        if not cluster_comps:
            continue
        xs = [positions[c["name"]][0] for c in cluster_comps]
        ys = [positions[c["name"]][1] for c in cluster_comps]
        pad = 50
        x1, y1 = min(xs) - pad, min(ys) - pad
        x2, y2 = max(xs) + pad, max(ys) + pad
        label = cluster_labels.get(cluster_name, cluster_name)
        svg_parts.append(
            f'<rect x="{x1}" y="{y1}" width="{x2-x1}" height="{y2-y1}" '
            f'rx="8" fill="#f5f5f5" stroke="#ddd" stroke-width="1"/>'
        )
        svg_parts.append(
            f'<text x="{x1+8}" y="{y1+16}" font-size="11" fill="#999" '
            f'font-family="sans-serif" font-weight="600">{label}</text>'
        )

    # Edges (draw before nodes so they're behind)
    # Deduplicate: one edge per (from, to) pair, strongest type wins
    edge_map = {}
    for conn in connections:
        key = (conn["from"], conn["to"])
        if key not in edge_map:
            edge_map[key] = conn
    # Also skip self-loops and connections to components not in our set
    comp_names = {c["name"] for c in components}
    for (src, tgt), conn in edge_map.items():
        if src not in positions or tgt not in positions:
            continue
        if src == tgt:
            continue
        x1, y1 = positions[src]
        x2, y2 = positions[tgt]
        proto = conn.get("protocol", "tcp")
        color = {"osc": "#e65100", "websocket": "#1565c0", "http": "#2e7d32",
                 "tcp": "#999"}.get(proto, "#999")
        opacity = "0.3"
        svg_parts.append(
            f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" '
            f'stroke="{color}" stroke-width="1.5" opacity="{opacity}"/>'
        )

    # Nodes
    for comp in components:
        if comp["name"] not in positions:
            continue
        x, y = positions[comp["name"]]
        lang = comp["language"]
        color = lang_color(lang)
        target = comp.get("compileTarget")
        total_loc = comp.get("totalLoc", 0)
        r = max(8, min(30, int(5 + math.sqrt(total_loc) / 8)))

        if target:
            target_color = lang_color(target)
            profile = comp.get("languageProfile", {})
            source_loc = profile.get(lang, {}).get("loc", 0)
            runtime_loc_val = profile.get(target, {}).get("loc", 0)
            total_relevant = source_loc + runtime_loc_val
            if total_relevant > 0:
                source_frac = source_loc / total_relevant
            else:
                source_frac = 1.0
            source_frac = max(0.08, min(0.92, source_frac))
            # Base circle = runtime language
            svg_parts.append(
                f'<circle cx="{x}" cy="{y}" r="{r}" fill="{target_color}" '
                f'stroke="white" stroke-width="2" opacity="0.9"/>'
            )
            # Source language wedge
            svg_parts.append(pie_wedge(x, y, r, source_frac, color))
        else:
            svg_parts.append(
                f'<circle cx="{x}" cy="{y}" r="{r}" fill="{color}" '
                f'stroke="white" stroke-width="2" opacity="0.9"/>'
            )

        name = comp["name"]
        if len(name) > 20:
            name = name[:18] + "..."
        svg_parts.append(
            f'<text x="{x}" y="{y + r + 14}" text-anchor="middle" '
            f'font-size="9" fill="#333" font-family="sans-serif">{name}</text>'
        )
        if comp.get("ports"):
            port_str = ", ".join(str(p) for p in comp["ports"][:2])
            svg_parts.append(
                f'<text x="{x}" y="{y - r - 5}" text-anchor="middle" '
                f'font-size="8" fill="#888" font-family="monospace">:{port_str}</text>'
            )

    svg_parts.append('</svg>')

    # Protocol legend
    legend = """
    <div class="legend">
        <div class="legend-item"><svg width="20" height="10"><line x1="0" y1="5" x2="20" y2="5" stroke="#e65100" stroke-width="2"/></svg> OSC</div>
        <div class="legend-item"><svg width="20" height="10"><line x1="0" y1="5" x2="20" y2="5" stroke="#1565c0" stroke-width="2"/></svg> WebSocket</div>
        <div class="legend-item"><svg width="20" height="10"><line x1="0" y1="5" x2="20" y2="5" stroke="#2e7d32" stroke-width="2"/></svg> HTTP</div>
    </div>
    """

    # Language legend — include both source and compile-target languages
    lang_legend_items = []
    seen_langs = set()
    for c in components:
        for lang_key in [c["language"], c.get("compileTarget")]:
            if lang_key and lang_key not in seen_langs:
                seen_langs.add(lang_key)
                col = lang_color(lang_key)
                lang_legend_items.append(
                    f'<div class="legend-item">'
                    f'<span class="lang-dot" style="background:{col}"></span>'
                    f'{lang_key}</div>'
                )
    lang_legend = f'<div class="legend">{"".join(lang_legend_items)}</div>'

    svg_str = "\n".join(svg_parts)

    return f"""
<section>
    <h2>System Topology</h2>
    <p>Components grouped by subsystem. Transpiled components are pie charts:
       base color is the runtime language, wedge is the source language,
       proportional to LOC on disk. Size indicates total LOC.
       Edges show inferred connections.</p>
    {legend}
    {lang_legend}
    <div class="figure">
        {svg_str}
        <p class="figure-caption">Figure 1 &mdash; Component topology with subsystem clustering</p>
    </div>
</section>"""


def generate_treemap_section(components, languages):
    """Generate a treemap of components colored by language."""
    W, H = 1000, 400

    # Get per-component LOC from the languages data... we don't have it per component
    # in the scan JSON. Use file counts as proxy, or just use equal sizing grouped by language.
    # For now, group by language and size by total LOC for that language.

    # Actually, let's make a language breakdown bar + component grid
    total_loc = sum(v["loc"] for v in languages.values())
    if total_loc == 0:
        return ""

    # Language bar
    bar_parts = [f'<svg viewBox="0 0 {W} 40" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;">']
    x = 0
    lang_items = sorted(languages.items(), key=lambda x: -x[1]["loc"])
    for lang, stats in lang_items:
        pct = stats["loc"] / total_loc
        w = pct * W
        if w < 1:
            continue
        color = lang_color(lang)
        bar_parts.append(
            f'<rect x="{x}" y="0" width="{w}" height="30" fill="{color}" '
            f'opacity="0.85"/>'
        )
        if w > 50:
            bar_parts.append(
                f'<text x="{x + w/2}" y="19" text-anchor="middle" '
                f'font-size="10" fill="white" font-family="sans-serif" '
                f'font-weight="600">{lang} {pct*100:.0f}%</text>'
            )
        x += w
    bar_parts.append('</svg>')

    # Component grid — each component as a small card
    grid_items = []
    for comp in sorted(components, key=lambda c: (-{"service":3,"executable":2,"binary":2,"library":1}.get(c["role"],0), c["name"])):
        color = lang_color(comp["language"])
        target = comp.get("compileTarget")
        role_class = f"role-{comp['role']}"
        ports = ""
        if comp.get("ports"):
            ports = f'<span style="color:#888;font-size:0.75rem"> :{",".join(str(p) for p in comp["ports"][:2])}</span>'
        target_label = ""
        right_border = ""
        if target:
            target_color = lang_color(target)
            target_label = f'<span style="color:#888;font-size:0.7rem">→{target}</span>'
            right_border = f"border-right:4px solid {target_color};"
        grid_items.append(
            f'<div style="display:inline-flex;align-items:center;gap:0.3rem;'
            f'margin:0.2rem 0.4rem;padding:0.25rem 0.5rem;'
            f'background:white;border:1px solid #e0e0e0;border-radius:4px;'
            f'border-left:4px solid {color};{right_border}font-size:0.8rem;">'
            f'<span class="role-badge {role_class}">{comp["role"][:3]}</span>'
            f'<strong>{comp["name"]}</strong>{target_label}{ports}</div>'
        )

    bar_svg = "\n".join(bar_parts)

    # Runtime bar — attribute each component's LOC to its compile target
    runtime_loc = {}
    for comp in components:
        loc = comp.get("totalLoc", 0)
        if not loc:
            continue
        target = comp.get("compileTarget")
        runtime_lang = target if target else comp["language"]
        runtime_loc[runtime_lang] = runtime_loc.get(runtime_lang, 0) + loc
    runtime_total = sum(runtime_loc.values())
    runtime_bar_parts = [f'<svg viewBox="0 0 {W} 40" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;">']
    x = 0
    for lang, loc in sorted(runtime_loc.items(), key=lambda x: -x[1]):
        pct = loc / runtime_total if runtime_total else 0
        w = pct * W
        if w < 1:
            continue
        color = lang_color(lang)
        runtime_bar_parts.append(
            f'<rect x="{x}" y="0" width="{w}" height="30" fill="{color}" opacity="0.85"/>'
        )
        if w > 50:
            runtime_bar_parts.append(
                f'<text x="{x + w/2}" y="19" text-anchor="middle" '
                f'font-size="10" fill="white" font-family="sans-serif" '
                f'font-weight="600">{lang} {pct*100:.0f}%</text>'
            )
        x += w
    runtime_bar_parts.append('</svg>')
    runtime_bar_svg = "\n".join(runtime_bar_parts)

    grid = "\n".join(grid_items)

    return f"""
<section>
    <h2>Language Breakdown</h2>
    <h3>Source files on disk</h3>
    <div class="figure">
        {bar_svg}
        <p class="figure-caption">Figure 2a &mdash; Lines of code by language (source files on disk)</p>
    </div>
    <h3>Runtime languages</h3>
    <div class="figure">
        {runtime_bar_svg}
        <p class="figure-caption">Figure 2b &mdash; LOC by runtime language (PureScript&rarr;JS/Erlang, TypeScript&rarr;JS, etc.)</p>
    </div>
    <h3>Components</h3>
    <div style="display:flex;flex-wrap:wrap;gap:0;margin:1rem 0;">
        {grid}
    </div>
</section>"""


def generate_flow_section(components, connections):
    """Generate a port-centric flow diagram."""
    W, H = 1000, 380

    # Find the hub ports
    port_refs = {}
    for conn in connections:
        if conn["type"] == "port-reference":
            port = conn["port"]
            port_refs.setdefault(port, {"sources": set(), "targets": set(), "proto": conn.get("protocol", "tcp")})
            port_refs[port]["sources"].add(conn["from"])
            port_refs[port]["targets"].add(conn["to"])

    # Top hub ports by connection count
    hub_ports = sorted(port_refs.items(), key=lambda x: -(len(x[1]["sources"]) + len(x[1]["targets"])))[:5]

    if not hub_ports:
        return ""

    svg_parts = [f'<svg viewBox="0 0 {W} {H}" xmlns="http://www.w3.org/2000/svg" style="width:100%;height:auto;">']

    # Layout: hub ports as vertical bars in the center, sources on left, targets on right
    center_x = W // 2
    port_spacing = H // (len(hub_ports) + 1)

    for i, (port, info) in enumerate(hub_ports):
        py = (i + 1) * port_spacing
        proto = info["proto"]
        color = {"osc": "#e65100", "websocket": "#1565c0", "http": "#2e7d32"}.get(proto, "#999")

        # Port label in center
        svg_parts.append(
            f'<rect x="{center_x - 40}" y="{py - 15}" width="80" height="30" '
            f'rx="4" fill="{color}" opacity="0.15" stroke="{color}" stroke-width="1.5"/>'
        )
        svg_parts.append(
            f'<text x="{center_x}" y="{py + 4}" text-anchor="middle" '
            f'font-size="12" fill="{color}" font-family="monospace" font-weight="700">:{port}</text>'
        )

        # Sources on left
        sources = sorted(info["sources"])
        for j, src in enumerate(sources[:6]):
            sx = 50 + (j % 3) * 120
            sy = py - 30 + (j // 3) * 25
            svg_parts.append(
                f'<text x="{sx + 50}" y="{sy + 4}" text-anchor="end" '
                f'font-size="9" fill="#333" font-family="sans-serif">{src}</text>'
            )
            svg_parts.append(
                f'<line x1="{sx + 55}" y1="{sy}" x2="{center_x - 42}" y2="{py}" '
                f'stroke="{color}" stroke-width="1" opacity="0.3" '
                f'marker-end="url(#arrow-{proto})"/>'
            )

        # Targets on right
        targets = sorted(info["targets"])
        for j, tgt in enumerate(targets[:6]):
            tx = center_x + 100 + (j % 3) * 120
            ty = py - 30 + (j // 3) * 25
            svg_parts.append(
                f'<text x="{tx}" y="{ty + 4}" text-anchor="start" '
                f'font-size="9" fill="#333" font-family="sans-serif">{tgt}</text>'
            )
            svg_parts.append(
                f'<line x1="{center_x + 42}" y1="{py}" x2="{tx - 5}" y2="{ty}" '
                f'stroke="{color}" stroke-width="1" opacity="0.3"/>'
            )

    # Arrow markers
    for proto, color in [("osc", "#e65100"), ("websocket", "#1565c0"), ("http", "#2e7d32"), ("tcp", "#999")]:
        svg_parts.append(
            f'<defs><marker id="arrow-{proto}" markerWidth="8" markerHeight="6" '
            f'refX="8" refY="3" orient="auto"><path d="M0,0 L8,3 L0,6" '
            f'fill="{color}" opacity="0.5"/></marker></defs>'
        )

    svg_parts.append('</svg>')
    svg_str = "\n".join(svg_parts)

    return f"""
<section>
    <h2>Signal Flow</h2>
    <p>Hub ports at center, with components that reference each port arranged
       by direction (sources left, listeners right). Color indicates protocol.</p>
    <div class="figure">
        {svg_str}
        <p class="figure-caption">Figure 3 &mdash; Port-centric signal flow (top 5 hub ports)</p>
    </div>
</section>"""


def generate_component_table(components, connections):
    """Generate a detailed component table."""
    rows = []
    conn_count = {}
    for c in connections:
        conn_count[c["from"]] = conn_count.get(c["from"], 0) + 1
        conn_count[c["to"]] = conn_count.get(c["to"], 0) + 1

    for comp in sorted(components, key=lambda c: -conn_count.get(c["name"], 0)):
        color = lang_color(comp["language"])
        role_class = f"role-{comp['role']}"
        ports = ", ".join(f":{p}" for p in comp.get("ports", []))
        n_conn = conn_count.get(comp["name"], 0)
        total_loc = comp.get("totalLoc", 0)

        # Language profile as a mini stacked bar
        profile = comp.get("languageProfile", {})
        bar_width = 120
        bar_parts = []
        if profile and total_loc > 0:
            x = 0
            for plang, pstats in profile.items():
                w = max(1, pstats["pct"] / 100 * bar_width) if pstats["pct"] >= 0.5 else 0
                if w > 0:
                    pcolor = lang_color(plang)
                    title = f"{plang}: {pstats['loc']} LOC ({pstats['pct']}%)"
                    bar_parts.append(
                        f'<rect x="{x}" y="0" width="{w}" height="12" '
                        f'fill="{pcolor}" opacity="0.8"><title>{title}</title></rect>'
                    )
                    x += w
            bar_svg = (
                f'<svg width="{bar_width}" height="12" style="vertical-align:middle">'
                + "".join(bar_parts)
                + '</svg>'
            )
        else:
            bar_svg = ""

        lang_label = comp["language"]
        if comp.get("compileTarget"):
            lang_label += f"→{comp['compileTarget']}"

        loc_display = f"{total_loc:,}" if total_loc else ""

        rows.append(
            f'<tr>'
            f'<td><span class="lang-dot" style="background:{color}"></span>'
            f'<strong>{comp["name"]}</strong></td>'
            f'<td><span class="role-badge {role_class}">{comp["role"]}</span></td>'
            f'<td>{lang_label}</td>'
            f'<td style="text-align:right;font-family:monospace;font-size:0.8rem">{loc_display}</td>'
            f'<td>{bar_svg}</td>'
            f'<td style="font-family:monospace;font-size:0.8rem">{ports}</td>'
            f'<td style="text-align:center">{n_conn}</td>'
            f'<td style="color:#888;font-size:0.8rem">{comp["path"]}</td>'
            f'</tr>'
        )

    table_rows = "\n".join(rows)
    return f"""
<section>
    <h2>Component Inventory</h2>
    <table>
        <thead>
            <tr>
                <th>Component</th>
                <th>Role</th>
                <th>Language</th>
                <th>LOC</th>
                <th>Language Profile</th>
                <th>Ports</th>
                <th>Connections</th>
                <th>Path</th>
            </tr>
        </thead>
        <tbody>
            {table_rows}
        </tbody>
    </table>
</section>"""


def main():
    args = sys.argv[1:]
    if not args or args[0] in ("-h", "--help"):
        print(__doc__.strip())
        sys.exit(0)

    scan_path = Path(args[0])
    scan_data = json.loads(scan_path.read_text())

    html = generate_report(scan_data)

    out_file = "portolan-report.html"
    if "--out" in args:
        idx = args.index("--out")
        if idx + 1 < len(args):
            out_file = args[idx + 1]

    Path(out_file).write_text(html)
    print(f"Report written to {out_file}")


if __name__ == "__main__":
    main()
